/* =====================================================================
   DEEP-DIVE LESSONS — the broader narrative for each module.
   Loaded after data.js; attaches to window.COURSE.LESSONS.
   Each lesson is an array of sections: { h, p } (+ optional code, lang).
   `p` may use \n\n for paragraph breaks and `backticks` for inline code.
   ===================================================================== */
window.COURSE = window.COURSE || {};
window.COURSE.LESSONS = {
  /* =============================================================== F1 */
  f1: [
    { h: "Why Go has a garbage collector at all",
      p: "In languages like C or C++ you allocate memory and you are responsible for freeing it again with `free`/`delete`. Get it wrong and you hit the three classic bugs: a *use-after-free* (touching memory you already returned), a *double-free* (returning the same block twice), or a *leak* (never returning it). These bugs are a huge source of crashes and security holes. Go makes a deliberate trade: it manages memory for you automatically, so you almost never write `free`, at the cost of spending a little CPU on a background collector. For server software that runs for months, that trade is almost always worth it." },
    { h: "The one question the GC keeps asking",
      p: "The entire job of the collector is to answer: *which objects can the program still reach?* It starts from a set of roots — every goroutine's stack and the package-level (global) variables — and follows pointers. Anything it can reach is live and kept; anything it cannot reach is garbage and its memory is reclaimed.\n\nThis single idea explains the most common Go memory leak: a long-lived map or slice that keeps pointers to objects you are 'done' with. As long as that container is reachable, everything it points to is reachable too, so the GC can never free it. The fix is never to call free — it is to drop the reference (delete the map entry, reslice, set to nil)." },
    { h: "Concurrent collection is why Go feels smooth",
      p: "Early garbage collectors 'stopped the world': they froze every thread, walked all of memory, then resumed. On a big heap that meant pauses of hundreds of milliseconds — fatal for a low-latency API. Go's collector instead runs *concurrently*, alongside your goroutines. There are still two stop-the-world moments (at the start and end of the mark phase), but they are tiny — typically well under a millisecond. This is the reason Go is a strong choice for latency-sensitive network services." },
    { h: "The pacer: the GC runs on growth, not on a clock",
      p: "A frequent misconception is that the GC runs on a timer. It does not. After each collection the runtime records how much memory is live and sets a target: run the next cycle once the heap has grown by `GOGC` percent. The default `GOGC=100` means 'collect again once the live heap has doubled'. The *pacer* is the controller that tries to schedule the concurrent mark so it finishes right as the heap reaches that target — not too early (wasted CPU) and not too late (heap overshoot)." },
    { h: "The two knobs, and when to touch them",
      p: "Ninety percent of programs never need to tune the GC. When you do, there are two levers. `GOGC` trades memory for CPU: raise it (e.g. 200, 400) for batch/throughput jobs that have RAM to spare and want fewer collections; the heap gets bigger but the GC runs less often. `GOMEMLIMIT` sets a soft ceiling on total memory — essential in containers, because it makes the GC work harder as you approach the limit instead of letting the kernel OOM-kill you. Anti-patterns: setting `GOGC` very low (CPU spikes) and calling `runtime.GC()` by hand in a hot path." },
    { h: "The cheapest collection is the allocation you avoid",
      p: "Here is the practical mental model for performance: GC CPU cost is roughly proportional to how much you allocate. So the biggest wins almost never come from tuning the collector — they come from allocating less. Reuse buffers (and `sync.Pool` for short-lived ones), prefer value types over pointers where it makes sense, preallocate slices and maps with a capacity hint, and avoid accidentally boxing values into interfaces inside tight loops. Use the heap profile's `alloc_space` view to find where the allocations actually come from before optimizing." },
    { h: "How to watch it happen",
      p: "You do not have to guess. `GODEBUG=gctrace=1 ./app` prints one line per cycle with pause times and heap sizes. `runtime.ReadMemStats` and the structured `runtime/metrics` package expose live numbers for dashboards. And the heap profile (Module F2) shows exactly which call sites allocate. Measure first, then decide whether any tuning is even worth it." },
  ],

  /* =============================================================== F2 */
  f2: [
    { h: "Why you must measure before you optimize",
      p: "Programmer intuition about performance is famously wrong. The function you 'know' is slow is often cheap, and the real cost hides somewhere boring — a logger, a JSON marshal, a needless allocation in a loop that runs a million times. Optimizing without measuring means you spend a day speeding up code that was never the bottleneck. A profiler removes the guessing: it tells you, with data, where the time and memory actually go." },
    { h: "How sampling profilers work",
      p: "Go's CPU profiler does not instrument every function call (that would be slow and distort the result). Instead it *samples*: about 100 times per second it interrupts the program and records the current call stack. Run for 30 seconds and you have ~3000 stack snapshots. A function that appears in 40% of the samples was, statistically, using ~40% of the CPU. More samples = more confidence, which is why you profile a representative workload for a meaningful duration." },
    { h: "Pick the profile that answers your question",
      p: "Different profiles answer different questions, and using the wrong one wastes time. Use the *CPU* profile for 'what is burning cycles'. Use the *heap* profile for memory — and know its two views: `inuse_space` (what is held right now, for finding leaks/bloat) and `alloc_space` (everything ever allocated, for finding GC pressure). Use the *goroutine* profile to find leaks and stuck goroutines. Use the *block* and *mutex* profiles to find contention where goroutines wait on each other." },
    { h: "Two ways to collect, one tool to read",
      p: "There are two collection paths. For a running service, blank-import `net/http/pprof` and it registers `/debug/pprof/*` endpoints — you pull a live profile without redeploying (bind it to an admin-only port). For a specific function, let `go test` write profiles to files with `-cpuprofile`/`-memprofile` under a benchmark. Either way, you read the result with the same tool, `go tool pprof`." },
    { h: "Reading a flame graph without getting fooled",
      p: "The flame graph is the fastest way to see where time goes, but it is easy to misread. Each box is a function; a box sitting *on top of* another means it was called by it. The crucial property is WIDTH: it is proportional to time (or allocations). So you optimize the *widest* boxes, especially wide leaves at the top. A tall, skinny tower is a deep call chain that costs almost nothing — ignore it. Beginners often chase height; experts chase width." },
    { h: "A repeatable workflow",
      p: "Put it together into a loop you can run any day: (1) reproduce the slow path under a benchmark or load test; (2) collect a CPU profile; (3) open the flame graph with `go tool pprof -http=:8080`; (4) find the widest leaf and read its source with `list`; (5) make one change; (6) re-profile to confirm it actually helped. Stop when the profile is flat — there is no single hotspot left to chase." },
  ],

  /* =============================================================== F3 */
  f3: [
    { h: "Testing is part of the language, not a library",
      p: "Many languages bolt testing on with a third-party framework full of macros and magic. Go builds it into the toolchain. You put tests in files ending `_test.go` next to the code they test, write functions named `TestXxx(t *testing.T)`, and run `go test`. There is no framework to learn, no annotations, no separate runner. This low ceremony is deliberate: the easier tests are to write, the more of them get written." },
    { h: "The table-driven test: Go's signature style",
      p: "The idiomatic Go test is *table-driven*. Instead of copy-pasting a test body for each case, you put the cases in a slice of structs and loop over them, running each with `t.Run` so it becomes a named subtest. Adding a new case is one line. When a case fails, the output names exactly which one. This pattern scales from three cases to three hundred without the test becoming unreadable, and it nudges you to think in terms of inputs and expected outputs." },
    { h: "Make failures debuggable",
      p: "A good test failure tells you what went wrong without opening a debugger. Always print both got and want: `t.Errorf(\"Add(2,3) = %d, want %d\", got, want)`. Use `t.Errorf` to record a failure and keep going (so you see all failing cases), and `t.Fatalf` to stop when continuing makes no sense (e.g. a setup step failed). Mark helper functions with `t.Helper()` so the failure points at the calling test line, not deep inside the helper." },
    { h: "Mocking without a mocking framework",
      p: "Go's secret weapon for testability is the interface. Instead of depending on a concrete type (a real database, a real clock, the real network), make your code depend on a small interface, and in tests pass a tiny fake struct that satisfies it. No mocking library, no code generation — just a struct with the methods you need. This keeps tests fast and deterministic and, as a bonus, pressures your design toward loose coupling." },
    { h: "Coverage and fuzzing: free safety nets",
      p: "Two built-in tools catch what hand-written cases miss. *Coverage* (`go test -cover`, then `go tool cover -html`) shows which lines your tests actually exercise — great for spotting an untested error branch. *Fuzzing* (`func FuzzXxx(f *testing.F)`) generates random inputs automatically and saves any input that crashes or trips an assertion; point it at anything that parses untrusted input and let it find the edge cases you would never think of." },
    { h: "The everyday command",
      p: "Internalize one command: `go test -race -cover ./...`. `-race` turns on the race detector, which catches data races (two goroutines touching the same memory without synchronization) — the single most valuable testing feature in a concurrent language. `-cover` keeps you honest about what is tested. Run it before every commit and wire it into CI." },
  ],

  /* =============================================================== F4 */
  f4: [
    { h: "Concurrency is about structure, not speed",
      p: "A common confusion: concurrency is not the same as parallelism. Parallelism is doing things at the same instant on multiple CPU cores. Concurrency is *structuring* a program as independent activities that can make progress when they are able to — handling many connections, waiting on several timeouts, pipelining stages. Go's goroutines and channels are tools for that structure; the runtime then maps it onto however many cores you have. You design concurrency; the runtime decides parallelism." },
    { h: "Goroutines are cheap, but they are not free",
      p: "A goroutine starts with about a 2 KB stack that grows on demand, so launching thousands is normal and launching a million is possible. But 'cheap to start' is not 'free to forget'. Every goroutine you start needs an owner who knows when it should stop. A goroutine that blocks forever on a channel nobody will ever send to is a *leak*: it holds its stack and anything it references, and the GC can never reclaim it. The rule: never start a goroutine without knowing how it ends." },
    { h: "Channels: synchronize or decouple",
      p: "A channel is a typed pipe, and its buffering changes its meaning. An *unbuffered* channel is a rendezvous: the sender blocks until a receiver is ready, so it both transfers a value and synchronizes the two goroutines at that instant. A *buffered* channel (capacity N) lets the sender run ahead by up to N values before it blocks — it decouples producer and consumer speeds. Choosing buffered vs unbuffered is choosing whether you want a handshake or a queue." },
    { h: "The ownership rules that prevent panics",
      p: "Two simple ownership rules eliminate most channel bugs. First, the *sender* closes a channel — never the receiver — and closes it exactly once; closing twice, or sending on a closed channel, panics. Closing signals 'no more values', which lets a `for v := range ch` loop end cleanly. Second, for shared mutable state that is not being passed between goroutines, reach for a `sync.Mutex` or `sync/atomic` instead of a channel. The slogan is 'share memory by communicating', but a mutex around a counter is simpler and correct — use the right tool." },
    { h: "select, context, and clean shutdown",
      p: "`select` lets one goroutine wait on several channel operations at once — combine a results channel with a `ctx.Done()` channel and a `time.After` timeout, and the first one ready wins. This is how you build cancellation and timeouts. The standard way to tell a tree of goroutines to stop is `context.Context`: pass it down, have each goroutine `select` on `ctx.Done()`, and a single `cancel()` (or a timeout) unwinds the whole tree. A long-running goroutine without a context is a leak waiting to happen." },
    { h: "The worker pool: the workhorse pattern",
      p: "The pattern you will reach for constantly is the worker pool. *Fan-out*: start a fixed number N of worker goroutines that all read from one `jobs` channel, so work spreads across them and concurrency is bounded to N (which protects downstream systems from overload). *Fan-in*: every worker writes to one shared `results` channel, merging their output for a single collector. Close `jobs` when there is no more work, and the workers drain and exit. Bounded, simple, and the basis of most real Go concurrency." },
  ],

  /* =============================================================== F5 */
  f5: [
    { h: "Errors are values, and that changes how you code",
      p: "Go has no exceptions. A function that can fail returns an `error` as its last result, and you handle it immediately with `if err != nil`. This feels verbose coming from try/catch, but it is a feature: every failure path is visible right where it happens, in order, with no invisible jumps across the stack. You cannot accidentally ignore an error the way an uncaught exception silently unwinds — the compiler and `errcheck` linters make unhandled errors stand out." },
    { h: "Wrap on the way up, inspect at the boundary",
      p: "As an error travels up the call stack, you want to add context (what were we doing?) without losing the original cause. That is wrapping: `fmt.Errorf(\"charge account %s: %w\", id, err)`. The `%w` verb is the key — it keeps the wrapped error reachable so a caller can still inspect it. At the top (an HTTP handler, say) you *unwrap*: `errors.Is(err, ErrNotFound)` checks for a known sentinel anywhere in the chain, and `errors.As(err, &target)` pulls out a specific error type to read its fields. Wrap low, inspect high." },
    { h: "Designing your error types",
      p: "Three tools cover almost everything. *Sentinel errors* (`var ErrNotFound = errors.New(\"not found\")`) are predefined values callers branch on with `errors.Is`. *Wrapped errors* add context with `%w`. *Custom error types* carry structured data — implement `Error() string`, and add `Unwrap() error` so they play nicely with `errors.Is/As`. A good rule: return sentinels for conditions callers act on, wrap everything else with enough context to debug from a log line alone." },
    { h: "Context: cancellation and deadlines, propagated",
      p: "`context.Context` solves a distributed-systems problem: when a client disconnects or a request times out, every goroutine and downstream call working on that request should stop, so you do not waste CPU and connections on a result nobody wants. You create a derived context with a timeout or cancel function, pass it as the *first argument* to everything it touches, and always `defer cancel()`. Cancelling a parent cancels all its children. The cardinal sins: storing a context in a struct field (breaks the request-scoped lifetime) and using `context.WithValue` as a general argument bag (it is for request-scoped metadata like trace IDs, not parameters)." },
    { h: "Project layout: structure that scales",
      p: "Go projects stay flat until they need not to. Two conventions do the heavy lifting. `cmd/<app>/main.go` holds entry points whose only job is wiring — parse config, build dependencies, start the server. `internal/` holds packages that *only your module* can import, enforced by the compiler — a real boundary that stops other teams (or your future self) from depending on internals. Name packages for the capability they provide (`ledger`, `postgres`), not for an architectural layer (`models`, `utils`); a package called `utils` is where cohesion goes to die." },
  ],

  /* =============================================================== M1 */
  m1: [
    { h: "What a router actually does",
      p: "Every HTTP server needs to answer one question for each request: given this method and path, which function should handle it? That mapping is routing. For years Go developers reached for third-party routers (gin, chi, echo) because the standard `http.ServeMux` could only match path prefixes — no method matching, no path variables. Since Go 1.22 that gap is closed: the standard mux matches `GET /api/v1/ledger/{id}` patterns directly, so most services can delete the dependency and the indirection that comes with it." },
    { h: "How the mux matches: the radix trie",
      p: "Internally the mux stores routes in a *radix trie* — a tree where each node is a path segment, so shared prefixes share nodes. Matching a request walks the tree segment by segment, which is fast and scales to many routes. Two rules matter in practice. Method and path are matched together, so `GET /x` and `POST /x` are different routes. And precedence is *most-specific-wins*: `/ledger/{id}/audit` beats `/ledger/{id}`, and a literal segment beats a wildcard — so you no longer have to register routes in a careful order." },
    { h: "Path variables and the end of regexp routers",
      p: "A `{id}` segment in the pattern is a wildcard; in the handler you read it with `r.PathValue(\"id\")`. No regular expressions, no router-specific `Context`, no allocation-heavy match objects. When a path matches but the method does not, the mux automatically responds `405 Method Not Allowed` with the correct `Allow` header — behavior you used to get from a library, now built in." },
    { h: "os.Root: making path traversal impossible, not unlikely",
      p: "Any time a server reads a file based on user input — a config name, an upload key, a template — it risks *path traversal*: an attacker sends `../../etc/passwd` (or a sneaky symlink) to escape the intended directory. The old defense was string checks like rejecting `..`, but attackers are endlessly creative with encodings and links, so validation is a losing game. `os.Root` (Go 1.24) flips it: you open a directory once, and every operation through that handle is physically confined to it at the syscall level. An escape attempt returns an error. You stop *validating* and start making the bad thing *impossible*." },
    { h: "Where this fits in the ledger",
      p: "In the capstone, this module builds the front door: the public REST gateway that ingests transactions, with zero third-party routing imports, and a config/storage loader jailed under `os.Root`. Getting the foundation dependency-free and traversal-proof here pays off in every later module — fewer moving parts to secure, audit, and upgrade." },
  ],

  /* =============================================================== M2 */
  m2: [
    { h: "Serialization is where servers spend surprising time",
      p: "A network service does two things constantly: turn bytes from the wire into Go values, and turn Go values back into bytes. That is serialization, and at high throughput it is often a top entry in the CPU profile. The default `encoding/json` is wonderfully convenient — it uses reflection to handle any type — but reflection has a cost paid on every call. For a ledger pushing millions of payloads, that cost is the difference between two servers and twenty." },
    { h: "json/v2 and streaming tokens",
      p: "`encoding/json/v2` keeps the easy high-level API but is faster and far more configurable, and it exposes a low-level streaming layer, `jsontext`, that emits or consumes JSON one token at a time. Streaming matters because it avoids building the whole document (or an intermediate `map[string]any`) in memory — you write tokens straight to the connection and read them straight off it. For large or high-volume payloads that is both faster and dramatically lighter on the garbage collector." },
    { h: "Memory geometry: why layout is performance",
      p: "Modern CPUs are bottlenecked on memory, not arithmetic. Fetching a byte already in the L1 cache is ~1 nanosecond; fetching from main memory is ~100×slower. So performance is largely about *cache locality* — keeping the data you need next to each other. This is the lens for the rest of the module: Swiss-Table maps win by touching one cache line per lookup, and stack allocation wins by keeping short-lived data off the heap entirely." },
    { h: "Swiss Tables: the same map, quietly rebuilt",
      p: "Go 1.24 reimplemented the built-in `map` as a *Swiss Table* with no API change. The old map chased bucket-overflow pointers, scattering across memory on collisions. The Swiss Table stores entries in groups of 8 with a compact one-byte tag per slot; a lookup hashes to a group, loads its 8 control bytes (one cache line), and compares all 8 in parallel with SIMD-style instructions, usually finding the answer with a single memory access. You changed nothing and your maps got faster and lighter." },
    { h: "Stack vs heap, and why you should care",
      p: "Every value lives either on a goroutine's stack (cheap: freed automatically when the function returns, zero GC involvement) or on the heap (managed by the GC). The compiler runs *escape analysis* to decide: if it can prove a value does not outlive the function, it stays on the stack. A transient encode buffer that never escapes costs the GC nothing. You can see the decisions with `go build -gcflags='-m'` and look for 'does not escape' — a practical habit when tuning a hot path." },
  ],

  /* =============================================================== M3 */
  m3: [
    { h: "Lifecycles: doing work when an object dies",
      p: "Most of the time the GC silently reclaiming memory is exactly what you want. But sometimes an object owns a resource the GC does not understand — an OS file descriptor, a C handle, a lock — and that resource must be released when the object is gone. The old tool, `runtime.SetFinalizer`, was notoriously dangerous: it could *resurrect* an object during finalization, ran in an undefined order, and delayed collection by an extra GC cycle. It caused more bugs than it solved." },
    { h: "runtime.AddCleanup, the right way",
      p: "Go 1.24's `runtime.AddCleanup` replaces finalizers with something predictable: a cleanup that runs exactly once, after the object is truly unreachable, with no resurrection. The critical discipline is what the cleanup *captures*. If the cleanup closure captures the object it is cleaning, the object stays reachable forever — the exact leak you were trying to prevent. Capture only the primitive resource handle (the fd, an int) by value, never the parent struct. Treat cleanups as a safety backstop, not your primary close path; explicit `Close()` / `defer` is still better when you can." },
    { h: "Interning: when a million rows share five strings",
      p: "A ledger with millions of accounts stores the currency code on every one — but there are only a handful of distinct currencies. Storing 'USD' a million times wastes megabytes. *Interning* via the `unique` package canonicalizes equal values to a single shared copy: `unique.Make(\"USD\")` returns a `Handle[string]` that is 8 bytes, points at one shared backing string, and — bonus — compares by pointer instead of byte-by-byte. Intern high-repetition, low-cardinality values like currencies, statuses, and label keys; do not intern unbounded unique strings or the global table just grows." },
    { h: "Weak pointers: caches that respect memory pressure",
      p: "Sometimes you want to remember an object *if it is still around* but never to be the reason it stays alive — a cache is the classic case. A normal pointer in a cache keeps its target alive forever, turning the cache into a leak. The `weak` package (Go 1.24) gives you a reference that does not prevent collection; you read it back and either get the object or `nil` if the GC reclaimed it. That lets you build caches that automatically shrink under memory pressure." },
    { h: "A peek at the scheduler (G-M-P)",
      p: "Understanding why Go scales helps you reason about performance. The runtime multiplexes many goroutines (G) onto a small number of OS threads (M) via logical processors (P, count = GOMAXPROCS). When a goroutine blocks on I/O, the runtime parks it in the *netpoller* and frees its thread to run other goroutines — so a server handling 100k idle connections does not need 100k threads. *Asynchronous preemption* lets the runtime interrupt even a tight CPU loop so it cannot starve everything else. This is why idiomatic Go concurrency is both simple to write and efficient to run." },
  ],

  /* =============================================================== M4 */
  m4: [
    { h: "Why concurrent tests go flaky",
      p: "A test is *flaky* when it passes and fails non-deterministically — green locally, red in CI, green on a rerun. The usual culprit in concurrent code is timing: the test starts a goroutine and then does `time.Sleep(100 * time.Millisecond)` hoping the goroutine has finished by then. On a loaded CI machine 100ms is not enough, so it fails; bump it to 500ms and the suite crawls. Sleeping to synchronize is guessing, and guessing is what makes tests flaky." },
    { h: "synctest: a bubble with a fake clock",
      p: "`testing/synctest` (stable in Go 1.25) removes the guessing. It runs your goroutines inside a *bubble* with a virtual clock. Inside the bubble, `time.Sleep`, timers, and tickers are simulated: when every goroutine in the bubble is blocked, the fake clock jumps instantly to the next scheduled timer. A `time.Sleep(5 * time.Second)` returns in microseconds of real time, but the code believes five seconds passed — so time-dependent logic is tested deterministically, with zero real waiting and zero flakiness." },
    { h: "synctest.Wait: assert on a settled world",
      p: "The companion to the fake clock is `synctest.Wait`, which blocks until every *other* goroutine in the bubble is durably blocked — i.e. the system has reached a steady state and nothing more will happen without external input. That replaces 'sleep and hope it scheduled' with a precise barrier: wait for quiescence, then assert. As a bonus, if everything in the bubble is durably blocked with no timer to fire, that is a deadlock, and synctest fails the test immediately instead of hanging your CI for the full timeout." },
    { h: "Benchmarks you can trust: b.Loop()",
      p: "The flip side of correctness is measurement, and benchmarks have their own footguns. The classic `for i := 0; i < b.N; i++` loop is easy to get subtly wrong: the compiler can delete work whose result you ignore (dead-code elimination), making code look faster than it is. Go 1.24's `for b.Loop()` fixes this — it keeps the benchmarked values alive automatically and runs setup once, giving stable, honest numbers without manual bookkeeping." },
    { h: "Determinism as a discipline",
      p: "The deeper lesson is that *determinism is a design goal*, not an accident. Tests that depend on wall-clock time, real network latency, or goroutine scheduling order will eventually flake. synctest virtualizes time; interfaces (Module F3) virtualize the clock and the network; the race detector catches the rest. A suite that is fully deterministic is one you can actually trust to gate deploys — the whole point of having tests." },
  ],

  /* =============================================================== M5 */
  m5: [
    { h: "The database is where correctness gets hard",
      p: "Stateless application code is easy to reason about; the moment you involve a database with concurrent writers, you inherit a century of hard-won ideas about consistency. For a financial ledger the stakes are highest — money must never be created or destroyed by a race. This module is about building that persistence layer in Go so it is both correct under concurrency and fast under load." },
    { h: "sqlc: move SQL errors to compile time",
      p: "There is a spectrum from raw SQL strings (fast, but a typo'd column blows up at runtime) to a heavyweight ORM (convenient, but it hides the queries and reflects at runtime). `sqlc` sits in a sweet spot: you write real SQL, and it generates type-safe Go functions from your queries plus the schema. A wrong column name or argument type now fails at code-generation time, not at 3am in production. You keep full control of the SQL and gain compile-time safety — no ORM magic." },
    { h: "Connection pools are not optional",
      p: "Opening a Postgres connection is expensive, and the database can only handle so many at once, so you never open one per request — you share a pool. `pgxpool` needs real configuration: `MaxConns` sized to what the database can handle (more is not better — each connection costs the server memory), `MaxConnLifetime` so connections recycle around load balancers and failovers, and context-aware queries so that when a client disconnects, the in-flight query is cancelled at the server instead of running on for nobody." },
    { h: "Row-level locks and the double-entry invariant",
      p: "The heart of a ledger is *double-entry*: every transfer debits one account and credits another by the same amount, so the total never changes. Under concurrency, two transfers touching the same account can race. The fix is a *row-level lock*: `SELECT ... FOR UPDATE` locks just the rows you are changing (not the whole table), so a second transaction touching the same account waits until the first commits. A subtle but critical rule: always lock multiple rows in a consistent order, or two transactions locking the same pair in opposite orders will deadlock." },
    { h: "Expect conflicts, and retry them",
      p: "Under serializable isolation the database may *refuse* a transaction that lost a race, returning SQLSTATE `40001` (serialization_failure). This is not a bug — it is the database protecting your invariant — and the correct response is to retry the whole transaction. Go 1.26's `errors.AsType[*pgconn.PgError]` lets you match the exact SQLSTATE cleanly and branch: retry `40001`, surface `23505` (unique_violation) as a duplicate, and so on. Designing for retryable failures is what makes a ledger correct *and* available under contention." },
  ],

  /* =============================================================== M6 */
  m6: [
    { h: "Talking between services, and the threat to that traffic",
      p: "Once a system spans more than one machine, services must talk over the network — and that traffic must stay private and compatible across versions. This module covers both: gRPC + Protobuf for efficient, evolvable inter-service calls, and post-quantum cryptography to keep the traffic secret against a threat that does not fully exist yet but is coming." },
    { h: "gRPC and Protobuf: contracts that evolve",
      p: "gRPC runs RPCs over HTTP/2 carrying *Protobuf* messages — a compact binary format defined by a schema. The schema is a contract between services that are deployed independently, so the discipline is *backward compatibility*: you may add new optional fields, but you must never reuse a retired field number or change a field's type, or an old node and a new node will silently misinterpret the same bytes. `reserved` retired numbers, and gate every schema change with a breaking-change check in CI so a v2 node never breaks a v1 peer mid-rollout." },
    { h: "Harvest now, decrypt later",
      p: "Here is the threat that justifies post-quantum crypto today. A patient adversary records your encrypted traffic *now* and simply stores it, waiting for a future quantum computer powerful enough to break today's key exchange (RSA, elliptic curves like X25519 all fall to Shor's algorithm). For data with a long shelf life — financial records, health data — 'we'll be fine for years' is the wrong frame: the traffic is being captured today and decrypted later. The defense must be deployed before the quantum computer exists." },
    { h: "Hybrid key exchange: belt and suspenders",
      p: "The answer is *hybrid* key exchange: combine a classical algorithm (X25519) with a post-quantum one (ML-KEM, a lattice-based scheme standardized by NIST as `crypto/mlkem`). The session key is derived from both, so an attacker must break *both* to recover it. This hedges the newness of the PQC algorithms — if ML-KEM turns out to have a flaw, you still have classical security, and vice versa. In Go you enable it by preferring the `X25519MLKEM768` group in your `tls.Config`; both peers must support it for it to be chosen." },
    { h: "Encoding invariants in the type system",
      p: "At staff level you push correctness into the compiler. The self-referencing generic constraint `type Node[T Node[T]] interface { ... }` lets a method return the *concrete* implementing type rather than the interface — so cluster-topology rules that would otherwise be runtime assertions become compile-time guarantees. Fewer invariants checked at runtime means fewer ways production can surprise you." },
  ],

  /* =============================================================== M7 */
  m7: [
    { h: "The worst time to add observability is during the incident",
      p: "Production failures are often transient: a latency spike, a brief deadlock, a leak that only shows under a specific load. By the time you SSH in to look, the moment has passed — and the classic response, 'add more logging and redeploy', changes the system and may not reproduce the bug. The goal of this module is to capture *what was happening just before* a failure, continuously and cheaply, so you can diagnose the first occurrence instead of waiting for the second." },
    { h: "The FlightRecorder: always-on, pay-on-demand",
      p: "`runtime/trace`'s FlightRecorder keeps a bounded ring buffer of recent execution events in memory at near-zero cost — like an aircraft's black box, it is always recording but only the last few seconds. You pay the cost of writing a trace to disk *only when something interesting happens*: a latency alarm fires, a panic handler runs, a health check fails. The result is the window leading up to the failure, captured at the moment of failure, without the overhead of continuous tracing." },
    { h: "Trigger on SLOs, capture a full picture",
      p: "Wire the recorder to the things you already watch. When p99 latency crosses your SLO, or a panic unwinds, atomically dump three things together: the flight trace (what executed), a goroutine profile (who was stuck and where), and a heap profile (what memory looked like). Gate dumps behind a cooldown so a flapping alarm does not bury you in files. Now an incident leaves behind a complete, correlated snapshot instead of a vague log line." },
    { h: "Reading the trace: go tool trace",
      p: "A trace file opens in `go tool trace` as an interactive timeline of every goroutine, GC cycle, syscall, and scheduler event. This is the microscope for 'why did this 50ms request take 50ms': you can see whether the time went to GC, to lock contention, to a slow syscall, or to a goroutine waiting on a channel. Logs tell you *what* happened; a trace shows you *where the time went*." },
    { h: "Leaks: from log spelunking to a generated report",
      p: "A goroutine that blocks forever — on a channel with no sender, a `WaitGroup` that never reaches zero, a context with no deadline — is a leak: it never exits, holding its stack and references. Historically you found these by squinting at goroutine dumps for hours. The goroutine-leak analyzer traces each blocked goroutine back to its root cause automatically, and you can assert 'no goroutines leaked' at test boundaries to catch regressions before they ship. Combined with always-giving-every-context-a-deadline, this turns a whole class of production mysteries into a routine check." },
  ],

  /* =============================================================== M8 */
  m8: [
    { h: "Hardware sympathy: working with the machine, not against it",
      p: "At the highest level of performance, you stop treating the CPU as an abstract instruction-executor and start writing code that fits how the hardware actually works — 'mechanical sympathy'. This module is three facets of that: using the CPU's vector units to do more per instruction, keeping secrets out of memory dumps, and a garbage collector redesigned around cache locality. None of it is everyday code, but knowing it exists — and when it is worth it — is what separates senior from principal." },
    { h: "Optimize the scalar loop before reaching for SIMD",
      p: "Before exotic techniques, make the ordinary loop fast, because the compiler is on your side. Ranging over a slice (rather than indexing) lets it prove indices are in range and remove per-iteration *bounds checks*. Keeping hot functions small lets it *inline* them, erasing call overhead. You can see both with `go build -gcflags='-m'` (inlining/escape) and `-gcflags='-d=ssa/check_bce/debug=1'` (remaining bounds checks). Often this alone closes most of the gap — and it is portable, unlike SIMD." },
    { h: "SIMD: one instruction, many values",
      p: "A scalar loop processes one element per iteration. A CPU's *SIMD* (Single Instruction, Multiple Data) units can apply one operation to a whole vector — 16 bytes, 8 floats — at once. For a loop that touches every byte of a block (a checksum, a validation pass), that is often an order-of-magnitude speedup. The experimental `simd/archsimd` package exposes these vector types in Go. The catch: vector instructions are architecture-specific, so you always keep a *scalar fallback* for the tail elements and for CPUs without the intrinsics. Only vectorize a loop the profiler proved is hot." },
    { h: "Secrets should not outlive their use",
      p: "A decrypted key sitting in an ordinary `[]byte` is a liability: it lingers in RAM, gets copied around by the moving garbage collector, and can end up in a core dump or swapped to disk — long after you needed it. `runtime/secret` holds sensitive bytes in a buffer that stays off the movable heap and is guaranteed to be zeroed on `Destroy`, shrinking the window during which a key is recoverable to the minimum. Minimizing that exposure window is a core defensive habit for anything handling key material." },
    { h: "Green Tea: a GC built for cache locality",
      p: "The experimental Green Tea collector (`GOEXPERIMENT=greenteagc`) reflects the same memory-is-the-bottleneck reality as Swiss Tables. Instead of marking objects one at a time and chasing pointers all over the heap (scattered, cache-unfriendly), it scans memory in contiguous 8 KiB *spans* — sequential access that the CPU prefetches well and that parallelizes cleanly across cores. On large heaps this can meaningfully cut GC CPU. As always: evaluate and benchmark against the default before adopting an experiment." },
  ],

  /* =============================================================== M9 */
  m9: [
    { h: "From a working binary to a system you can operate",
      p: "Code that runs on your laptop is a long way from a service a team can deploy, scale, and upgrade at 3am without dropping requests. This module is about that last mile: making Go behave well inside containers, shipping images that are small and hard to attack, automating large-scale code changes, and recording the decisions so the next engineer is not guessing. Principal engineers are judged as much on operability as on cleverness." },
    { h: "Let the runtime see the container's real limits",
      p: "A pod is limited by Linux *cgroups* to, say, 4 CPUs and 512 MB — but historically the Go runtime saw the *host's* 128 cores and set GOMAXPROCS to 128, spawning far too many threads and thrashing under the kernel's CPU throttling. Go 1.25 reads the cgroup CPU quota and sets GOMAXPROCS to match automatically. Pair it with `GOMEMLIMIT` set to the memory limit so the GC works harder near the ceiling instead of getting OOM-killed. The lesson: a containerized runtime must respect the container's limits, not the host's." },
    { h: "Hardened images: ship the binary, nothing else",
      p: "A statically linked, CGO-free Go binary needs no operating system to run. So a production image should contain essentially just that binary. A multi-stage Docker build compiles in a full toolchain image, then copies the single binary into `scratch` (empty) or a `distroless` base — a few megabytes, no shell, no package manager, and therefore a tiny CVE surface and nothing for an attacker to pivot to. Run as a non-root user. Small and boring is exactly what you want in production." },
    { h: "Changing code across a fleet without heroics",
      p: "When you maintain libraries used by many teams, deprecating an API is painful — you cannot file a hundred PRs. The overhauled `go fix` engine plus `//go:fix` inline directives let you ship *machine-applicable* migrations: mark the old API, and every consumer runs `go fix ./...` to auto-rewrite their call sites safely. This turns a coordination nightmare into a one-command upgrade and is how large Go codebases stay current instead of accreting deprecated calls forever." },
    { h: "Write down why, not just what",
      p: "The final discipline is organizational. An *Architecture Decision Record* is a short, append-only note capturing the context, the options considered, the decision, and its consequences — for instance, 'we chose hybrid ML-KEM for inter-node transport because of the harvest-now-decrypt-later threat to 30-year ledger data'. Six months later, when someone asks 'why is the handshake slower?', the answer is in the ADR instead of in someone's memory. Code shows *what*; ADRs preserve *why*." },
    { h: "Rolling updates: upgrade with zero dropped requests",
      p: "Putting it together, a deploy should be invisible to users. Kubernetes does a *rolling update*: it starts a new-version pod, waits for its *readiness probe* to pass before sending it any traffic, then drains an old pod (stop new requests, let in-flight ones finish) before terminating it — repeating pod by pod. Health and readiness probes are the contract that makes this safe. Build them in, and 'deploy' stops being a scary word." },
  ],
};
