/* =====================================================================
   UI CHROME STRINGS - every hardcoded label/button/heading in app.js,
   keyed by language. Course CONTENT (modules, lessons, etc.) lives in
   data.js / data.ru.js / lessons.js / lessons.ru.js instead.
   ===================================================================== */
window.UI_STRINGS = {
  en: {
    docTitle: "Hardcore Go & Distributed Systems Engineering - Interactive Course",
    docDescription: "An interactive, local-first course for production-grade Go 1.24-1.26 and distributed systems engineering.",
    courseHome: "Course Home",
    filterModules: "Filter modules…",
    searchModulesLabel: "Search course modules",
    noSearchResults: "No modules found",
    clearFilter: "Clear filter",
    toggleTheme: "Toggle theme",
    toggleLangAria: "Switch language to Russian",
    toggleLang: "Русский",
    home: "Home",
    viewFirstModule: "View first module",
    continue: "Continue",
    start: "Start",
    modules: "modules",
    tracks: "tracks",
    animations: "animations",
    moduleScope: "Lesson + viz + practice",
    selfPaced: "self-paced",
    modulesComplete: "modules complete",
    capstoneProject: "Capstone project",
    capstoneTagline: "- every module builds one system: a",
    capstoneFooter: "Zero-dependency, high-throughput, post-quantum secure.",
    productionChecklist: "Production Verification Checklist",
    footer: "Local course · progress saved in your browser (localStorage) · no server, no tracking.",
    inPlainTerms: "In plain terms",
    tryItYourself: "Try it yourself",
    deepDive: "Deep dive - the bigger picture",
    sections: "sections",
    workedExample: "Worked example - step by step",
    steps: "steps",
    runnableGo: "runnable Go",
    why: "Why:",
    keyTerms: "Key terms",
    coreConcepts: "Core Engineering Concepts",
    learnFaster: "Learn faster with an AI tutor",
    copyPrompt: "Copy prompt",
    promptNote: "Copy this and paste it into an AI assistant (Claude, Cursor, …) to run the AI-assisted workflow for this topic on",
    promptNoteEm: "your own",
    promptNoteEnd: "code.",
    notesPlaceholder: "Jot insights, gotchas, links… (saved locally)",
    notesLabel: "Your notes",
    saved: "saved ✓",
    allModules: "All modules",
    finish: "Finish ✓",
    ledgerBuild: "Ledger build",
    assignments: "Assignments",
    solved: "solved",
    answerIntro: "Answer below - checked instantly in your browser. Multiple-choice and fill-in-the-blank are graded exactly; “write code” tasks are checked structurally (rule by rule), not compiled.",
    checkAnswer: "Check answer",
    explanation: "Explanation",
    hideExplanation: "Hide explanation",
    yourAnswer: "your answer…",
    writeGoHere: "// write your Go here",
    allChecksPass: "✓ All checks pass - nice.",
    notAllChecksPass: "Not all checks pass yet - fix the ✗ items above.",
    correct: "✓ Correct!",
    notQuite: "✗ Not quite - try again, then hit Explanation.",
    mcq: "Multiple choice",
    blank: "Fill in the blank",
    predict: "Predict the output",
    code: "Write code",
    resetToStart: "Reset to start",
    nudgeBack: "Nudge back",
    playPause: "Play / pause (space)",
    nudgeForward: "Nudge forward",
    playbackSpeed: "Playback speed",
    scrubTimeline: "Scrub visualization timeline",
    step: "Step",
    courseModules: "Course modules",
    checklistTitle: "Module Checklist",
    openMenu: "Open navigation menu",
    menu: "menu",
    copy: "copy",
    copied: "copied ✓",
    moduleWord: "Module",
    complete: "complete",
    interactiveViz: "Interactive visualization · step-by-step",
    readyPrompt: "Ready-made prompt - paste into Claude or Cursor",
    commonPitfalls: "Common pitfalls",
    keyTakeaways: "Key takeaways",
    masteryChecklist: "Mastery checklist",
    resetModule: "Reset module",
    markAllComplete: "Mark all complete",
    yourNotes: "Your notes",
    brandSubtitle: "Distributed Systems Engineering",
  },
  ru: {
    docTitle: "Hardcore Go и инженерия распределённых систем - интерактивный курс",
    docDescription: "Интерактивный локальный курс по production-grade Go 1.24-1.26 и инженерии распределённых систем.",
    courseHome: "Главная курса",
    filterModules: "Фильтр модулей…",
    searchModulesLabel: "Поиск модулей курса",
    noSearchResults: "Ничего не найдено",
    clearFilter: "Сбросить фильтр",
    toggleTheme: "Сменить тему",
    toggleLangAria: "Переключить язык на English",
    toggleLang: "English",
    home: "Главная",
    viewFirstModule: "К первому модулю",
    continue: "Продолжить",
    start: "Начать",
    modules: "модулей",
    tracks: "разделов",
    animations: "анимаций",
    moduleScope: "Урок + график + практика",
    selfPaced: "в своём темпе",
    modulesComplete: "модулей пройдено",
    capstoneProject: "Финальный проект",
    capstoneTagline: "- каждый модуль строит одну систему:",
    capstoneFooter: "Без зависимостей, высокая пропускная способность, постквантовая защита.",
    productionChecklist: "Чек-лист готовности к продакшену",
    footer: "Локальный курс · прогресс сохраняется в браузере (localStorage) · без сервера, без слежки.",
    inPlainTerms: "Простыми словами",
    tryItYourself: "Попробуйте сами",
    deepDive: "Глубже в тему - общая картина",
    sections: "разделов",
    workedExample: "Пример с разбором - шаг за шагом",
    steps: "шагов",
    runnableGo: "рабочий Go-код",
    why: "Почему:",
    keyTerms: "Ключевые термины",
    coreConcepts: "Основные инженерные концепции",
    learnFaster: "Учитесь быстрее с AI-помощником",
    copyPrompt: "Скопировать промпт",
    promptNote: "Скопируйте и вставьте в AI-ассистента (Claude, Cursor, …), чтобы прогнать AI-сценарий по этой теме на",
    promptNoteEm: "своём",
    promptNoteEnd: "коде.",
    notesPlaceholder: "Заметки, нюансы, ссылки… (сохраняется локально)",
    notesLabel: "Ваши заметки",
    saved: "сохранено ✓",
    allModules: "Все модули",
    finish: "Завершить ✓",
    ledgerBuild: "Сборка леджера",
    assignments: "Задания",
    solved: "решено",
    answerIntro: "Отвечайте ниже - проверка происходит мгновенно в браузере. Тесты с выбором ответа и пропуски проверяются точно; задания «написать код» проверяются структурно (по правилам), без компиляции.",
    checkAnswer: "Проверить ответ",
    explanation: "Объяснение",
    hideExplanation: "Скрыть объяснение",
    yourAnswer: "ваш ответ…",
    writeGoHere: "// напишите ваш Go-код здесь",
    allChecksPass: "✓ Все проверки пройдены - отлично.",
    notAllChecksPass: "Пока пройдены не все проверки - исправьте пункты с ✗ выше.",
    correct: "✓ Верно!",
    notQuite: "✗ Не совсем - попробуйте ещё раз, затем откройте объяснение.",
    mcq: "Выбор ответа",
    blank: "Заполните пропуск",
    predict: "Предскажите вывод",
    code: "Напишите код",
    resetToStart: "Сбросить в начало",
    nudgeBack: "Шаг назад",
    playPause: "Пуск / пауза (пробел)",
    nudgeForward: "Шаг вперёд",
    playbackSpeed: "Скорость воспроизведения",
    scrubTimeline: "Перемотка таймлайна визуализации",
    step: "Шаг",
    courseModules: "Модули курса",
    checklistTitle: "Чек-лист модуля",
    openMenu: "Открыть меню навигации",
    menu: "меню",
    copy: "копировать",
    copied: "скопировано ✓",
    moduleWord: "Модуль",
    complete: "пройден",
    interactiveViz: "Интерактивная визуализация · по шагам",
    readyPrompt: "Готовый промпт - вставьте в Claude или Cursor",
    commonPitfalls: "Частые ошибки",
    keyTakeaways: "Главные выводы",
    masteryChecklist: "Чек-лист освоения",
    resetModule: "Сбросить модуль",
    markAllComplete: "Отметить всё пройденным",
    yourNotes: "Ваши заметки",
    brandSubtitle: "Инженерия распределённых систем",
  },
};
