/* =====================================================================
   UI CHROME STRINGS - every hardcoded label/button/heading in app.js,
   keyed by language. Course CONTENT (modules, lessons, etc.) lives in
   data.js / data.ru.js / lessons.js / lessons.ru.js instead.
   ===================================================================== */
window.UI_STRINGS = {
  en: {
    docTitle: "Hardcore Go & Distributed Systems Engineering - Interactive Course",
    docDescription: "An interactive, local-first course for production-grade Go 1.24-1.26 and distributed systems engineering.",
    courseHome: "Course Home",
    filterModules: "Filter modules…",
    searchModulesLabel: "Search course modules",
    noSearchResults: "No modules found",
    clearFilter: "Clear filter",
    toggleTheme: "Toggle theme",
    toggleLangAria: "Switch language to Russian",
    toggleLang: "Русский",
    home: "Home",
    viewFirstModule: "View first module",
    continue: "Continue",
    start: "Start",
    modules: "modules",
    tracks: "tracks",
    animations: "animations",
    moduleScope: "Lesson + viz + practice",
    selfPaced: "self-paced",
    modulesComplete: "modules complete",
    capstoneProject: "Capstone project",
    capstoneTagline: "- every module builds one system: a",
    capstoneFooter: "Zero-dependency, high-throughput, post-quantum secure.",
    capstoneRoadmapTitle: "Distributed Financial Ledger roadmap",
    capstoneRoadmapIntro: "This is the final project: every module contributes one production capability to the same ledger system.",
    capstoneRoadmapOpen: "Open module",
    moduleBuildTitle: "What this module adds to the ledger",
    practiceBuildTitle: "Practice step for the ledger",
    finalProjectCodeTitle: "Resulting project code",
    finalProjectCodeIntro: "A runnable zero-dependency Go 1.26 reference implementation of the Distributed Financial Ledger: sharded account state, idempotent transfers, HTTP API, structured logs and ML-KEM-768 post-quantum key material.",
    finalProjectCodeMeta: "8 files · go test ./...",
    productionChecklist: "Production Verification Checklist",
    footer: "Local course · progress saved in your browser (localStorage) · no server, no tracking.",
    inPlainTerms: "In plain terms",
    tryItYourself: "Try it yourself",
    deepDive: "Deep dive - the bigger picture",
    sections: "sections",
    workedExample: "Worked example - step by step",
    steps: "steps",
    runnableGo: "runnable Go",
    why: "Why:",
    keyTerms: "Key terms",
    videoLessons: "Video Lessons",
    watchOn: "Watch",
    openExternally: "Open externally ↗",
    coreConcepts: "Core Engineering Concepts",
    learnFaster: "Learn faster with an AI tutor",
    copyPrompt: "Copy prompt",
    promptNote: "Copy this and paste it into an AI assistant (Claude, Cursor, …) to run the AI-assisted workflow for this topic on",
    promptNoteEm: "your own",
    promptNoteEnd: "code.",
    notesPlaceholder: "Jot insights, gotchas, links… (saved locally)",
    notesLabel: "Your notes",
    saved: "saved ✓",
    allModules: "All modules",
    finish: "Finish ✓",
    ledgerBuild: "Ledger build",
    assignments: "Assignments",
    solved: "solved",
    answerIntro: "Answer below - checked instantly in your browser. Multiple-choice and fill-in-the-blank are graded exactly; “write code” tasks are checked structurally (rule by rule), not compiled.",
    checkAnswer: "Check answer",
    explanation: "Explanation",
    hideExplanation: "Hide explanation",
    yourAnswer: "your answer…",
    writeGoHere: "// write your Go here",
    allChecksPass: "✓ All checks pass - nice.",
    notAllChecksPass: "Not all checks pass yet - fix the ✗ items above.",
    correct: "✓ Correct!",
    notQuite: "✗ Not quite - try again, then hit Explanation.",
    mcq: "Multiple choice",
    blank: "Fill in the blank",
    predict: "Predict the output",
    code: "Write code",
    resetToStart: "Reset to start",
    nudgeBack: "Nudge back",
    playPause: "Play / pause (space)",
    nudgeForward: "Nudge forward",
    playbackSpeed: "Playback speed",
    scrubTimeline: "Scrub visualization timeline",
    step: "Step",
    courseModules: "Course modules",
    checklistTitle: "Module Checklist",
    openMenu: "Open navigation menu",
    menu: "menu",
    copy: "copy",
    copied: "copied ✓",
    moduleWord: "Module",
    complete: "complete",
    interactiveViz: "Interactive visualization · step-by-step",
    readyPrompt: "Ready-made prompt - paste into Claude or Cursor",
    commonPitfalls: "Common pitfalls",
    keyTakeaways: "Key takeaways",
    masteryChecklist: "Mastery checklist",
    resetModule: "Reset module",
    markAllComplete: "Mark all complete",
    moduleComplete: "Module complete!",
    moduleCompleteSub: "On to the next one.",
    yourNotes: "Your notes",
    brandSubtitle: "Distributed Systems Engineering",
    backToTop: "Back to top",
  },
  ru: {
    docTitle: "Hardcore Go и инженерия распределённых систем - интерактивный курс",
    docDescription: "Интерактивный локальный курс по production-grade Go 1.24-1.26 и инженерии распределённых систем.",
    courseHome: "Главная курса",
    filterModules: "Фильтр модулей…",
    searchModulesLabel: "Поиск модулей курса",
    noSearchResults: "Ничего не найдено",
    clearFilter: "Сбросить фильтр",
    toggleTheme: "Сменить тему",
    toggleLangAria: "Переключить язык на азербайджанский",
    toggleLang: "Azərbaycan",
    home: "Главная",
    viewFirstModule: "К первому модулю",
    continue: "Продолжить",
    start: "Начать",
    modules: "модулей",
    tracks: "разделов",
    animations: "анимаций",
    moduleScope: "Урок + график + практика",
    selfPaced: "в своём темпе",
    modulesComplete: "модулей пройдено",
    capstoneProject: "Финальный проект",
    capstoneTagline: "- каждый модуль строит одну систему:",
    capstoneFooter: "Без зависимостей, высокая пропускная способность, постквантовая защита.",
    capstoneRoadmapTitle: "Карта Distributed Financial Ledger",
    capstoneRoadmapIntro: "Это и есть финальный проект: каждый модуль добавляет одну production-возможность в одну и ту же систему леджера.",
    capstoneRoadmapOpen: "Открыть модуль",
    moduleBuildTitle: "Что этот модуль добавляет в леджер",
    practiceBuildTitle: "Практический шаг для леджера",
    finalProjectCodeTitle: "Результирующий проектный код",
    finalProjectCodeIntro: "Запускаемая zero-dependency реализация Distributed Financial Ledger на Go 1.26: sharded account state, идемпотентные переводы, HTTP API, structured logs и постквантовый ML-KEM-768 key material.",
    finalProjectCodeMeta: "8 файлов · go test ./...",
    productionChecklist: "Чек-лист готовности к продакшену",
    footer: "Локальный курс · прогресс сохраняется в браузере (localStorage) · без сервера, без слежки.",
    inPlainTerms: "Простыми словами",
    tryItYourself: "Попробуйте сами",
    deepDive: "Глубже в тему - общая картина",
    sections: "разделов",
    workedExample: "Пример с разбором - шаг за шагом",
    steps: "шагов",
    runnableGo: "рабочий Go-код",
    why: "Почему:",
    keyTerms: "Ключевые термины",
    videoLessons: "Видеоуроки",
    watchOn: "Смотреть",
    openExternally: "Открыть на сайте ↗",
    coreConcepts: "Основные инженерные концепции",
    learnFaster: "Учитесь быстрее с AI-помощником",
    copyPrompt: "Скопировать промпт",
    promptNote: "Скопируйте и вставьте в AI-ассистента (Claude, Cursor, …), чтобы прогнать AI-сценарий по этой теме на",
    promptNoteEm: "своём",
    promptNoteEnd: "коде.",
    notesPlaceholder: "Заметки, нюансы, ссылки… (сохраняется локально)",
    notesLabel: "Ваши заметки",
    saved: "сохранено ✓",
    allModules: "Все модули",
    finish: "Завершить ✓",
    ledgerBuild: "Сборка леджера",
    assignments: "Задания",
    solved: "решено",
    answerIntro: "Отвечайте ниже - проверка происходит мгновенно в браузере. Тесты с выбором ответа и пропуски проверяются точно; задания «написать код» проверяются структурно (по правилам), без компиляции.",
    checkAnswer: "Проверить ответ",
    explanation: "Объяснение",
    hideExplanation: "Скрыть объяснение",
    yourAnswer: "ваш ответ…",
    writeGoHere: "// напишите ваш Go-код здесь",
    allChecksPass: "✓ Все проверки пройдены - отлично.",
    notAllChecksPass: "Пока пройдены не все проверки - исправьте пункты с ✗ выше.",
    correct: "✓ Верно!",
    notQuite: "✗ Не совсем - попробуйте ещё раз, затем откройте объяснение.",
    mcq: "Выбор ответа",
    blank: "Заполните пропуск",
    predict: "Предскажите вывод",
    code: "Напишите код",
    resetToStart: "Сбросить в начало",
    nudgeBack: "Шаг назад",
    playPause: "Пуск / пауза (пробел)",
    nudgeForward: "Шаг вперёд",
    playbackSpeed: "Скорость воспроизведения",
    scrubTimeline: "Перемотка таймлайна визуализации",
    step: "Шаг",
    courseModules: "Модули курса",
    checklistTitle: "Чек-лист модуля",
    openMenu: "Открыть меню навигации",
    menu: "меню",
    copy: "копировать",
    copied: "скопировано ✓",
    moduleWord: "Модуль",
    complete: "пройден",
    interactiveViz: "Интерактивная визуализация · по шагам",
    readyPrompt: "Готовый промпт - вставьте в Claude или Cursor",
    commonPitfalls: "Частые ошибки",
    keyTakeaways: "Главные выводы",
    masteryChecklist: "Чек-лист освоения",
    resetModule: "Сбросить модуль",
    markAllComplete: "Отметить всё пройденным",
    moduleComplete: "Модуль пройден!",
    moduleCompleteSub: "Вперёд к следующему.",
    yourNotes: "Ваши заметки",
    brandSubtitle: "Инженерия распределённых систем",
    backToTop: "Наверх",
  },
  az: {
    docTitle: "Hardcore Go və Paylanmış Sistemlər Mühəndisliyi - İnteraktiv Kurs",
    docDescription: "Production səviyyəli Go 1.24-1.26 və paylanmış sistemlər mühəndisliyi üzrə interaktiv, lokal kurs.",
    courseHome: "Kursun Ana Səhifəsi",
    filterModules: "Modulları filtrləyin…",
    searchModulesLabel: "Kurs modullarında axtar",
    noSearchResults: "Heç bir modul tapılmadı",
    clearFilter: "Filtri təmizlə",
    toggleTheme: "Temanı dəyiş",
    toggleLangAria: "Dili İngilis dilinə dəyişdir",
    toggleLang: "English",
    home: "Ana səhifə",
    viewFirstModule: "İlk modula keç",
    continue: "Davam et",
    start: "Başla",
    modules: "modul",
    tracks: "bölmə",
    animations: "animasiya",
    moduleScope: "Dərs + vizuallaşdırma + təcrübə",
    selfPaced: "öz tempinizdə",
    modulesComplete: "modul tamamlandı",
    capstoneProject: "Yekun layihə",
    capstoneTagline: "- hər modul bir sistem qurur:",
    capstoneFooter: "Xarici asılılıqsız, yüksək tutumlu, postkvant təhlükəsiz.",
    capstoneRoadmapTitle: "Distributed Financial Ledger yol xəritəsi",
    capstoneRoadmapIntro: "Bu, yekun layihədir: hər modul eyni ledger sisteminə bir production imkanı əlavə edir.",
    capstoneRoadmapOpen: "Modulu aç",
    moduleBuildTitle: "Bu modul ledger-ə nə əlavə edir",
    practiceBuildTitle: "Ledger üçün təcrübə addımı",
    finalProjectCodeTitle: "Yekun layihə kodu",
    finalProjectCodeIntro: "Distributed Financial Ledger-in işlək, xarici asılılıqsız Go 1.26 istinad implementasiyası: shard-lanmış hesab vəziyyəti, idempotent köçürmələr, HTTP API, strukturlaşdırılmış loglar və ML-KEM-768 postkvant açar materialı.",
    finalProjectCodeMeta: "8 fayl · go test ./...",
    productionChecklist: "Production Yoxlama Siyahısı",
    footer: "Lokal kurs · irəliləyiş brauzerinizdə saxlanılır (localStorage) · server yoxdur, izləmə yoxdur.",
    inPlainTerms: "Sadə dillə",
    tryItYourself: "Özünüz sınayın",
    deepDive: "Dərinə enək - böyük mənzərə",
    sections: "bölmə",
    workedExample: "İzahlı nümunə - addım-addım",
    steps: "addım",
    runnableGo: "işlək Go",
    why: "Niyə:",
    keyTerms: "Əsas terminlər",
    videoLessons: "Video Dərslər",
    watchOn: "İzlə",
    openExternally: "Xaricdə aç ↗",
    coreConcepts: "Əsas Mühəndislik Anlayışları",
    learnFaster: "AI repetitorla daha sürətli öyrənin",
    copyPrompt: "Promptu kopyala",
    promptNote: "Bunu kopyalayıb AI köməkçisinə (Claude, Cursor və s.) yapışdıraraq bu mövzu üzrə AI-dəstəkli iş axınını",
    promptNoteEm: "öz",
    promptNoteEnd: "kodunuzda işə salın.",
    notesPlaceholder: "Fikirlər, tələlər, linklər yazın… (lokal saxlanılır)",
    notesLabel: "Qeydləriniz",
    saved: "saxlanıldı ✓",
    allModules: "Bütün modullar",
    finish: "Bitir ✓",
    ledgerBuild: "Ledger tikintisi",
    assignments: "Tapşırıqlar",
    solved: "həll edildi",
    answerIntro: "Cavabı aşağıda yazın - brauzerinizdə ani yoxlanılır. Çoxvariantlı və boşluq doldurma sualları dəqiq qiymətləndirilir; «kod yazın» tapşırıqları strukturca (qayda-qayda) yoxlanılır, kompilyasiya edilmir.",
    checkAnswer: "Cavabı yoxla",
    explanation: "İzahat",
    hideExplanation: "İzahatı gizlət",
    yourAnswer: "cavabınız…",
    writeGoHere: "// Go kodunuzu buraya yazın",
    allChecksPass: "✓ Bütün yoxlamalar keçdi - əla.",
    notAllChecksPass: "Hələ bütün yoxlamalar keçməyib - yuxarıdakı ✗ maddələrini düzəldin.",
    correct: "✓ Düzdür!",
    notQuite: "✗ Düz deyil - yenidən cəhd edin, sonra İzahata baxın.",
    mcq: "Çoxvariantlı sual",
    blank: "Boşluğu doldurun",
    predict: "Nəticəni proqnozlaşdırın",
    code: "Kod yazın",
    resetToStart: "Əvvələ qaytar",
    nudgeBack: "Bir addım geri",
    playPause: "İşə sal / dayandır (boşluq)",
    nudgeForward: "Bir addım irəli",
    playbackSpeed: "Oxutma sürəti",
    scrubTimeline: "Vizuallaşdırma xəttini sürüşdür",
    step: "Addım",
    courseModules: "Kurs modulları",
    checklistTitle: "Modul Yoxlama Siyahısı",
    openMenu: "Naviqasiya menyusunu aç",
    menu: "menyu",
    copy: "kopyala",
    copied: "kopyalandı ✓",
    moduleWord: "Modul",
    complete: "tamamlandı",
    interactiveViz: "İnteraktiv vizuallaşdırma · addım-addım",
    readyPrompt: "Hazır prompt - Claude və ya Cursor-a yapışdırın",
    commonPitfalls: "Tez-tez rast gəlinən səhvlər",
    keyTakeaways: "Əsas nəticələr",
    masteryChecklist: "Mənimsəmə siyahısı",
    resetModule: "Modulu sıfırla",
    markAllComplete: "Hamısını tamamlanmış qeyd et",
    moduleComplete: "Modul tamamlandı!",
    moduleCompleteSub: "Növbəti modula keçək.",
    yourNotes: "Qeydləriniz",
    brandSubtitle: "Paylanmış Sistemlər Mühəndisliyi",
    backToTop: "Yuxarı qayıt",
  },
};
